# Generated by Django 3.2.9 on 2022-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wash_price', models.DecimalField(decimal_places=2, help_text='Ex: 300', max_digits=11, max_length=255, verbose_name='Price')),
                ('type', models.CharField(choices=[('CAR', 'CAR'), ('MOTO', 'MOTO'), ('TRUCK', 'TRUCK')], default='CAR', help_text='Ex:Car', max_length=25, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='entry date')),
            ],
        ),
    ]
