# Generated by Django 3.2.9 on 2022-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0002_auto_20220115_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
