# Generated by Django 3.2.9 on 2022-01-15 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_delete_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={},
        ),
        migrations.AddField(
            model_name='employe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='employe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
