# Generated by Django 3.2.9 on 2022-01-23 19:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_auto_20220115_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('name', models.CharField(help_text='Ex:Extaz', max_length=150, unique=True, verbose_name='Name')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(help_text='Ex:+509XXXXXXXX', max_length=15, region=None, verbose_name='Phone')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ex:+509XXXXXXXX', max_length=15, region=None, verbose_name='Phone')),
                ('address', models.TextField(blank=True, help_text='Entrer address', null=True, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employe.restaurant'),
        ),
    ]
