# Generated by Django 3.2.9 on 2022-01-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20220123_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employe.restaurant'),
            preserve_default=False,
        ),
    ]
