# Generated by Django 3.2.9 on 2022-01-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_alter_employe_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employe.restaurant'),
        ),
    ]
