# Generated by Django 3.2.9 on 2022-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='night_price',
            field=models.DecimalField(decimal_places=2, default=False, help_text='Ex: 4000', max_digits=11, max_length=255, verbose_name='Night Price'),
            preserve_default=False,
        ),
    ]
