# Generated by Django 3.2.9 on 2021-11-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0003_auto_20211122_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ex: 30', max_digits=11, max_length=255, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
