# Generated by Django 3.2.9 on 2022-01-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
        ('ordered', '0005_delete_wineorderedline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashOrderedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity')),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordered.ordered')),
                ('wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wash.wash')),
            ],
        ),
    ]
