# Generated by Django 3.2.9 on 2022-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0007_auto_20220115_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='table',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='total',
        ),
        migrations.AddField(
            model_name='ordered',
            name='client',
            field=models.CharField(default='', help_text='Ex: John Doe', max_length=150, verbose_name='Client Name'),
            preserve_default=False,
        ),
    ]
