# Generated by Django 3.2.9 on 2022-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0008_auto_20220116_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
    ]
