# Generated by Django 3.2.9 on 2022-01-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
        ('ordered', '0009_ordered_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOrderedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('quantity', models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity')),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordered.ordered')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
