# Generated by Django 3.2.9 on 2022-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0010_roomorderedline'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomorderedline',
            name='is_night',
            field=models.BooleanField(default=False, verbose_name='Is Night'),
        ),
    ]
