# Generated by Django 3.2.9 on 2022-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0011_roomorderedline_is_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkorderedline',
            name='is_ml',
            field=models.BooleanField(default=False, verbose_name='Is Ml'),
        ),
    ]
