# Generated by Django 3.2.9 on 2022-01-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0012_drinkorderedline_is_ml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkorderedline',
            old_name='is_ml',
            new_name='is_shot',
        ),
    ]
