# Generated by Django 3.2.9 on 2021-11-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ex: 300', max_digits=11, max_length=255, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Ex: 30', max_digits=11, max_length=255, verbose_name='Discount')),
            ],
        ),
        migrations.CreateModel(
            name='MenuWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.wine')),
            ],
        ),
        migrations.CreateModel(
            name='MenuMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
    ]
