# Generated by Django 3.2.9 on 2022-01-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuWine',
        ),
    ]
