# Generated by Django 3.2.9 on 2022-01-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_menuwine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='total',
        ),
    ]
