# Generated by Django 3.2.9 on 2021-11-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex:Buger', max_length=150, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ex: 300', max_digits=11, max_length=255, verbose_name='Price')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Ex: 30', max_digits=11, max_length=255, verbose_name='Sale Price')),
                ('type', models.CharField(help_text='Ex:Main', max_length=150, verbose_name='Type')),
            ],
        ),
    ]
