# Generated by Django 3.2.9 on 2021-11-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
    ]
