# Generated by Django 3.2.9 on 2022-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220115_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='quantity_available',
            field=models.IntegerField(default=1, help_text='Ex: 1', verbose_name='Quantity available'),
        ),
    ]
