# Generated by Django 3.2.9 on 2021-11-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winegrower',
            name='first_name',
            field=models.CharField(help_text='Ex:john', max_length=150, null=True, verbose_name='Firstname'),
        ),
        migrations.AddField(
            model_name='winegrower',
            name='last_name',
            field=models.CharField(help_text='Ex:snow', max_length=150, null=True, verbose_name='Lastname'),
        ),
    ]
