# Generated by Django 3.2.9 on 2021-11-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_alter_wine_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Buy date'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
