# Generated by Django 3.2.9 on 2021-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0004_auto_20211122_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='buy_date',
            field=models.DateTimeField(verbose_name='Buy date'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date'),
        ),
    ]
