# Generated by Django 3.2.9 on 2021-11-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0005_auto_20211122_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='name',
            field=models.CharField(default='', help_text='Ex:Coca', max_length=150, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(default='', help_text='Ex:Main', max_length=150, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
