# Generated by Django 3.2.9 on 2021-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0006_auto_20211122_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(help_text='Ex:Bordeaux', max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(help_text='Ex:Rouge', max_length=150, verbose_name='Type'),
        ),
    ]
