# Generated by Django 3.2.9 on 2022-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered', '0005_delete_wineorderedline'),
        ('menu', '0004_delete_menuwine'),
        ('drink', '0007_auto_20211122_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry date'),
        ),
        migrations.AddField(
            model_name='drink',
            name='sale_price_ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Ex: 5', max_digits=11, max_length=255, verbose_name='Sale Price(ml)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('SOFT', 'SOFT'), ('BEER', 'BEER'), ('LIQUOR', 'LIQUOR')], default='SOFT', help_text='Ex:Soft drink', max_length=25, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
        migrations.DeleteModel(
            name='Winegrower',
        ),
    ]
