# Generated by Django 3.2.9 on 2022-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0008_auto_20220108_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='sale_price_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 5', max_digits=11, max_length=255, null=True, verbose_name='Sale Price(ml)'),
        ),
    ]
