# Generated by Django 3.2.9 on 2022-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0009_alter_drink_sale_price_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
