# Generated by Django 3.2.9 on 2022-01-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0014_rename_restuarant_drink_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='sale_price_ml',
            new_name='sale_price_shot',
        ),
    ]
